# Generated by Django 4.0.4 on 2022-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_client_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=30)),
                ('insurance_type', models.CharField(max_length=30)),
                ('insurance_period', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year_man', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('owner_type', models.CharField(max_length=30)),
                ('use_case', models.CharField(max_length=30)),
                ('tonage', models.CharField(max_length=30)),
                ('eng_capacity', models.CharField(max_length=30)),
                ('seating_capacity', models.CharField(max_length=30)),
                ('owner_names', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('owner_contacts', models.CharField(max_length=30)),
                ('reg_number', models.CharField(max_length=30)),
                ('pin_number', models.CharField(max_length=30)),
                ('valuation', models.CharField(max_length=30)),
                ('preferred_insurer', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('premium', models.CharField(max_length=30)),
                ('amount_paid', models.CharField(max_length=30)),
                ('payment_ref', models.CharField(max_length=30)),
                ('logbook_url', models.CharField(max_length=30)),
                ('natid_url', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='valuation_userdata_mysql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=302)),
                ('trim', models.CharField(default='standard', max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('how_used', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('descriptn', models.CharField(max_length=30)),
                ('eng_capacity', models.CharField(max_length=30)),
                ('year_man', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=30)),
                ('estm_value', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
