# Generated by Django 4.0.4 on 2022-06-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carValuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
