# Generated by Django 4.0.4 on 2022-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carValuation', '0002_customerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance_client_table',
            name='logbook_url',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='insurance_client_table',
            name='natid_url',
            field=models.CharField(max_length=225),
        ),
    ]
