# Generated by Django 4.0.4 on 2022-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carValuation', '0003_alter_insurance_client_table_logbook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_payments_table',
            fields=[
                ('transLoID', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('TransactionType', models.CharField(max_length=225)),
                ('TransID', models.CharField(max_length=225)),
                ('TransTime', models.CharField(max_length=225)),
                ('TransAmount', models.CharField(max_length=225)),
                ('BusinessShortCode', models.CharField(max_length=225)),
                ('BillRefNumber', models.CharField(max_length=225)),
                ('InvoiceNumber', models.CharField(max_length=225, null=True)),
                ('OrgAccountBalance', models.CharField(max_length=225)),
                ('ThirdPartyTransID', models.CharField(max_length=225, null=True)),
                ('MSISDN', models.CharField(max_length=225)),
                ('FirstName', models.CharField(max_length=225)),
                ('MiddleName', models.CharField(max_length=225, null=True)),
                ('LastName', models.CharField(default='NaN', max_length=225)),
            ],
        ),
    ]
