# Generated by Django 4.0.4 on 2022-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carValuation', '0004_client_payments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrating',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
